version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress.cmimzo2ep7xd.us-east-1.rds.amazonaws.com 
      WORDPRESS_DB_USER: wordpressAdmin
      WORDPRESS_DB_PASSWORD: $$asdasd123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs-26529ba5.efs.us-east-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
      device: "fs-26529ba5.efs.us-east-1.amazonaws.com:/"
